### ISSUE TITLE
How to determine the value of variable Lbox?

### ISSUE THREAD

**Issue by obaica** [llodeiro/DensityTool#5]
Thank you for sharing such an excellent program. I have read the **User_Manual** but am not sure how to set the value of variable **Lbox** (please see the below). 

#################################################
###VARIABLES NEEDED FROM PREVIOUS VASP CALCULATION

Ni          = 640			# Number of points along r_i

Lbox        = 75.199695		 	# Box length along r_i
#################################################

Also, I would like to know how to set parameters to get a series of PARCHG files according to the link below.

https://www.vasp.at/wiki/index.php/Band_decomposed_charge_densities

It would be very helpful if you could provide an example of how to use VASP to calculate a series of PARCHG files for users who are not familiar with VASP.

Thank you very much.

**Comment by llodeiro** [comment]
Hello,

The variable L_box in the plot.py scripts is the length of the NOT averaged
vector (r_3 if DIRECTION=3), and the value of this variable has to be set
equal to the cell vector norm.
You can calculate it from the CHGCAR file, using the scaling factor (2°
line) and the cell vector matrix (3°, 4° and 5° line). Also we upgrade the
code and this quantities are
currently printed into the output file of DensityTool.

About the VASP calculation itself, it is not our main point of focus, we
give some insight about this in to our paper:
https://authors.elsevier.com/c/1f0iM2OInkAIB
Also in the Examples/README file are links to the VASP examples, which are
very helpful, and the VASP wiki where you can find good explanations for
everything of VASP:
https://www.vasp.at/wiki/index.php/PARCHG
As you can see, currently  there are many examples for VASP calculations
and doing our own set would be redundant.

Whatever information or doubt you have, I am here.
Expecting you are ok, and you calculations be successful

Regards - Lucas Lodeiro

**Comment by obaica** [comment]
Thank you for your reply.

As far as I know, there are three different ways to obtain PARCHG files through VASP calculations, as follows (INCAR files).

```
#INCAR1
ISTART =      1    job   : 0-new  1-cont  2-samecut
ICHARG =      1   charge: 1-file 2-atom 10-const  
LPARD=.TRUE.
IBAND= 20 21 22 23
KPUSE= 1 2 3 4
LSEPB=.TRUE.
LSEPK=.TRUE.
```
```
#INCAR2
ISTART =      1    job   : 0-new  1-cont  2-samecut
ICHARG =      1   charge: 1-file 2-atom 10-const
LPARD=.TRUE.
EINT = -10.3 -5.1
LSEPB=.FALSE.
LSEPK=.FALSE.
```
```
#INCAR3
ISTART =      1    job   : 0-new  1-cont  2-samecut
ICHARG =      1   charge: 1-file 2-atom 10-const
LPARD=.TRUE.
NBMOD=-3
EINT = -1
LSEPB=.FALSE.
LSEPK=.FALSE.
```

I would like to know which INCAR input file you are using in your example. 

Thank you very much.

**Comment by llodeiro** [comment]
Hello,

We use the first one. AS is mentioned in the paper, LSEPB and LSEPK must be
set to TRUE. The way through select which particular states are printed
does not change the situation (I mean, through IBAND+KPUSE, Energy
window...).

Regards
